### ISSUE TITLE
Error sending messages from Telegram

### ISSUE THREAD

**Issue by registriren** [Neolysion/WTT-Bridge#9]
Sending messages from Whatsapp is correct, groups in Telegrams are created, but the answer does not pass - an error:

-------------
2019-06-01 02:10:26,617 - transitions.core - INFO - Exited state transport
2019-06-01 02:10:26,617 - transitions.core - INFO - Entered state transport
2019-06-01 02:10:31,789 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/root/WTT-Bridge/__env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 333, in process_update
    handler.handle_update(update, self, check, context)
  File "/root/WTT-Bridge/__env/lib/python3.6/site-packages/telegram/ext/handler.py", line 117, in handle_update
    return self.callback(update, context)
  File "/root/WTT-Bridge/src/telegram_bot.py", line 50, in onTextMessage
    if int(chatMap[key]["tgID"]) == tgID:
KeyError: 'tgID'
2019-06-01 02:10:36,617 - transitions.core - INFO - Exited state transport
2019-06-01 02:10:36,617 - transitions.core - INFO - Entered state transport
E 2019-06-01 02:10:36,617 yowsup.layers.interface.interface - Stream Error type: ack
{'ack': None}

2019-06-01 02:10:36,617 - yowsup.layers.interface.interface - ERROR - Stream Error type: ack
{'ack': None}

I 2019-06-01 02:10:36,617 yowsup.layers.interface.interface - Initiating reconnect
2019-06-01 02:10:36,617 - yowsup.layers.interface.interface - INFO - Initiating reconnect
2019-06-01 02:10:36,618 - transitions.core - INFO - Exited state transport
2019-06-01 02:10:36,618 - transitions.core - INFO - Entered state transport
2019-06-01 02:10:36,723 - transitions.core - INFO - Exited state transport
2019-06-01 02:10:36,723 - transitions.core - INFO - Entered state init
I 2019-06-01 02:10:36,723 yowsup.layers.network.layer - Connecting to e1.whatsapp.net:443
2019-06-01 02:10:36,723 - yowsup.layers.network.layer - INFO - Connecting to e1.whatsapp.net:443
2019-06-01 02:10:36,862 - transitions.core - INFO - Exited state init
2019-06-01 02:10:36,862 - transitions.core - INFO - Entered state init

**Comment by s-boris** [comment]
have you wiped the chatmap after this commit? @registriren https://github.com/Neolysion/WTT-Bridge/commit/b2686ff2157b673a8593b19a158b1bd5c79e44be
I had to change the format of the chatmap. If you want to keep the telegram groups you can also try to edit your chatmap and swap the title and waID (see commit message).

**Comment by registriren** [comment]
I did the install in an empty directory

chatmap.json
--------------
{"-31359xxxx": {"waID": "79xxxxxxxxx@s.whatsapp.net", "title": "[WA]\
u041e\u043b\u044f"}, "-3860xxxxx": {"waID": "79xxxxxxxxx-155926xxx7@g
.us", "title": "[WA]\u0422\u0435\u0441\u0442\u043e\u0432\u0430\u044f 
\u0433\u0440\u0443\u043f\u043f\u0430"}}

**Comment by registriren** [comment]
not formed the basis tgID

**Comment by s-boris** [comment]
ok, that looks alright. try if sending messages is fixed now with the latest version

**Comment by registriren** [comment]
worked, but there is another problem:
If the stop period of the service comes a message, an error occurs and a message in telegram. no one hits
2019-06-01 06:32:35,185 - src.whatsapp_layer - INFO - Groups updated
2019-06-01 06:32:36,186 - src.media_worker - INFO - Processing [url=https://mmg-fna.whatsapp.net/d/f/AthFekCJyTpeF4FDXafwXQCU43cjLipwmLwaUrcxxxxx.enc, media_key=b'nDybvoQtFQsCqq3axnHILtDJmgDTgvt41k2MhQxxxxx=']
Download       : 100%|#############| 61.0/61.0 [00:00<00:00, 382KB/s]Decrypt        : 100%|############| 61.0/61.0 [00:00<00:00, 109kKB/s]2019-06-01 06:32:37,477 - JobQueue - ERROR - An uncaught error was raised while executing job whatsappMessageListener
Traceback (most recent call last):
  File "/root/WTT-Bridge/__env/lib/python3.6/site-packages/telegram/ext/jobqueue.py", line 260, in tick
    job.run(self._dispatcher)
  File "/root/WTT-Bridge/__env/lib/python3.6/site-packages/telegram/ext/jobqueue.py", line 388, in run
    self.callback(CallbackContext.from_job(self, dispatcher))
  File "/root/WTT-Bridge/src/telegram_bot.py", line 79, in whatsappMessageListener
    sendToTelegram(context, msg)
  File "/root/WTT-Bridge/src/telegram_bot.py", line 92, in sendToTelegram
    chatName = "[WA]" + (msg.title if msg.isGroup else msg.author)
TypeError: must be str, not NoneType
2019-06-01 06:33:25,151 - transitions.core - INFO - Exited state transport

in the future, the reception is correctly

**Comment by registriren** [comment]
executed git pull, messages stopped coming in both directions...
chatmap.json was removed

PS: started receiving hung messages via yowsup-cli demos --yowsup -c ~/.config/yowsup/config/config.json , then re-launched the service and it worked

the problem of message delivery from Whatsapp during the stop WTT is still relevant

**Comment by s-boris** [comment]
I do get offline messages forwarded correctly as soon as I start WTT. 
There are some messages that don't get correctly decrypted (empty body or wrong attributes for example) but that's a yowsup problem and should be fixed with the next release. (media upload to whatsapp too according to the dev)

**Comment by registriren** [comment]
this is true, but if there is a file chatmap.json , if it is not present (first run) and there are pending WA messages , then it is not created

**Comment by s-boris** [comment]
> this is true, but if there is a file chatmap.json , if it is not present (first run) and there are pending WA messages , then it is not created

I think I understand what you mean.  I wasn't able reproduce the problem yet but this commit might fix it.

**Comment by registriren** [comment]
checked, now everything works correctly, thanks
